#include <HardwareSerial.h>

HardwareSerial ecSerial(1); // Use UART1 for EC-01
int counter = 1;

void sendAT(String cmd, int wait = 1000) {
  ecSerial.println(cmd);
  delay(wait);
  while (ecSerial.available()) {
    Serial.write(ecSerial.read());
  }
}

void setup() {
  Serial.begin(115200);
  ecSerial.begin(9600, SERIAL_8N1, 4, 5); // RX=4, TX=5 (ESP32 side)

  delay(2000); // Allow EC-01 to boot

  Serial.println("Initializing EC-01...");

  sendAT("AT");                         // Check module
  sendAT("AT+CGDCONT=1,\"IP\",\"nbiot\""); // Dialog NB-IoT APN
  sendAT("AT+CGATT=1", 3000);           // Attach to network
  sendAT("AT+CGACT=1,1", 3000);         // Activate PDP context

  // MQTT Config
  sendAT("AT+QMTCFG=\"version\",0,4");  // MQTT 3.1.1
  sendAT("AT+QMTCFG=\"keepalive\",0,60"); // Keep alive 60s

  // Open MQTT connection
  sendAT("AT+QMTOPEN=0,\"broker.hivemq.com\",1883", 5000);

  // Connect to broker (client ID auto-generated by EC-01 if empty)
  sendAT("AT+QMTCONN=0,\"\"", 2000); // "" means empty client ID
}

void loop() {
  String msg = String(counter);
  Serial.println("Publishing: " + msg);

  // Publish to your topic rashmikapico1
  sendAT("AT+QMTPUB=0,0,0,0,\"rashmikapico1\"");
  ecSerial.print(msg); 
  ecSerial.write(0x1A); // End of message (CTRL+Z)
  delay(2000); // Wait for EC-01 to process

  counter++;
  delay(3000); // Send every 3 seconds
}
